services:
  test:
    build: .
    container_name: weon_test
    command: pytest
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - db

  api:
    build: .
    container_name: weon_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/weon_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: weon_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
